spring:
  application:
    name: ${EUREKA_CLIENT:service-auth}
  servlet:
    multipart.max-file-size: 1MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: public

server:
  port: ${PORT:8801}

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    # preferIpAddress: true

logging:
  level:
    '[org.springframework]': ERROR

jwt:
  access-valid-time: 1800000 # 30 minute
  refresh-valid-time: 86400000 # 1 day
  base64-secret: ${JWT_SECRET}
