spring:
  application:
    name: ${EUREKA_CLIENT:service-data}

server:
  port: ${PORT:8030}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    # preferIpAddress: true
