spring:
  application:
    name: ${EUREKA_CLIENT:message}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: public
  artemis:
    mode: native
    broker-url: ${MESSAGE_BROKER_URL:tcp://localhost:61616}
    user: ${MESSAGE_BROKER_USERNAME:artemis}
    password: ${MESSAGE_BROKER_PASSWORD:artemis}
    # pool:
    #   enabled: true
    #   max-connections: 50

server:
  port: ${PORT:8050}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    # preferIpAddress: true

logging:
  level:
    # '[org.springframework]': DEBUG
    '[com.example]': DEBUG

queue:
  name: queue